#!/bin/sh

echo '>> Fixing WSL mounts'
fix-mounts

## System
lastfile=~/etc/latest-sync
: >> $lastfile
last=$(cat ~/etc/latest-sync)
now=$(date -u +%Y%m%d)
if (( now <= last ))
then
    echo '>> Skipping repository updates'
else
    echo $now > $lastfile

    echo '>> Updating repositories'
    doas emerge --sync
fi

echo '>> Updating packages'
doas emerge --update --deep --with-bdeps=y @world

echo '>> Removing orphaned packages'
doas emerge --depclean

echo '>> Updating package list'
list=~/etc/packages.list
cat /var/lib/portage/world > $list{new}
cmp -s $list{new} $list || mv -f $list{new} $list
rm -f $list{new}

## Nix
if which nix > /dev/null 2>&1
then
    echo '>> Updating Nix channels'
    nix-channel --update

    echo '>> Updating Nix packages'
    nix-env -iA nixpkgs.nix
fi

## Rust
if which rustup > /dev/null 2>&1
then
    echo '>> Updating rust'
    rustup update
fi

## Python
python=$(which python python3 python2 2> /dev/null | head -1 | sed 's:.*/::')
if [[ -z $python ]]
then
    echo '>> Python is not installed'
else
    if ! $python -m pip --version > /dev/null 2>&1
    then
        echo '>> Installing pip'
        f=$(mktemp)
        curl -L -o "$f" https://bootstrap.pypa.io/get-pip.py
        $python "$f" --user -qq
        rm -f "$f"
    else
        echo '>> Updating pip'
        $python -m pip install -U --no-python-version-warning --user pip
    fi

    echo '>> Updating python packages'
    $python -m pip list --format=json --no-python-version-warning --not-required \
    | jq -r '.[] | .name' \
    | xargs -r $python -m pip install -U --no-python-version-warning --upgrade-strategy=eager --user
fi

## Other
if [[ -d "$0.d" ]]
then
    for f in "$0.d"/*.sh
    do
        [[ -r "$f" && -x "$f" ]] && . "$f"
    done
fi
